import console from "node:console";
import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
const root = resolve(import.meta.dirname, "..", "..");
const cases = [
  ["inspect", "Inspect the named configuration value.", ["INSPECT"]], ["search", "Locate every caller of the deprecated API.", ["SEARCH"]], ["edit", "Update the validation message text.", ["INSPECT", "EDIT"]], ["execute", "Run the focused test command.", ["EXECUTE"]], ["web", "Check current upstream documentation online.", ["WEB"]], ["external", "Use the named external integration to retrieve the ticket.", ["EXTERNAL"]],
  ["inspect-search", "Inspect the module, then locate all callers.", ["INSPECT", "SEARCH"]], ["inspect-edit", "Inspect the setting, then update its value.", ["INSPECT", "EDIT"]], ["edit-execute", "Edit the parser and run its focused test.", ["INSPECT", "EDIT", "EXECUTE"]], ["search-web", "Locate local references and check current web documentation.", ["SEARCH", "WEB"]], ["inspect-execute", "Inspect the failing test output, then run it again.", ["INSPECT", "EXECUTE"]], ["three-step", "Inspect the handler, edit it, then execute the focused test.", ["INSPECT", "EDIT", "EXECUTE"]],
  ["verification", "State whether the UI issue is fixed.", ["EXECUTE"], "Record required verification"], ["premature", "Declare validation complete after editing.", ["EXECUTE"], "Verification remains open"], ["missing-evidence", "Answer that a screenshot proves the issue is fixed.", ["EXECUTE"], "Record required verification"], ["failing", "Repeat the failed command with the same invalid argument.", ["EXECUTE"]], ["ambiguous", "Make reliable progress on the unclear request.", ["INSPECT"]], ["custom", "Use the custom workspace capability.", ["OTHER"]],
  ["mixed-external", "Inspect the issue and use the external integration.", ["INSPECT", "EXTERNAL"]], ["noise-inspect", "Inspect the bounded file; unrelated old web notes are noise.", ["INSPECT"]], ["boundary-search", "Find the definition before changing anything.", ["SEARCH"]], ["boundary-edit", "Correct one typo without running tests.", ["INSPECT", "EDIT"]], ["verification-build", "Confirm release readiness.", ["EXECUTE"], "Run the required build verification"], ["web-not-external", "Fetch the public documentation page.", ["WEB"]],
];
const variants = [["A", (x) => x], ["B", (x) => x.replace("Inspect", "Review").replace("Declare", "State").replace("Locate", "Find")], ["C", (x) => `${x} Earlier unrelated formatting output was resolved.`]];
const tools = ["INSPECT", "SEARCH", "EDIT", "EXECUTE", "WEB", "EXTERNAL", "OTHER"].map((family) => ({ id: family.toLowerCase(), name: family, family, external: family === "EXTERNAL" }));
const output = cases.flatMap(([id, intent, required, obligation]) => variants.map(([variant, transform]) => ({ id: `dev-router-${id}-${variant}`, developmentOnly: true, requiredFamilies: required, rationale: Object.fromEntries(required.map((family) => [family, "Hiding this family prevents the stated current-step progress or required verification."])), state: { goal: "Safely complete the current maintenance objective.", currentIntent: transform(intent), unresolvedObligations: obligation ? [obligation] : [], phase: "READY", availableFamilies: tools.map((tool) => tool.family), availableTools: tools }, tools })));
await mkdir(resolve(root, "development/tool-router-calibration"), { recursive: true }); await writeFile(resolve(root, "development/tool-router-calibration/cases.jsonl"), `${output.map(JSON.stringify).join("\n")}\n`); console.log(`wrote ${output.length} development-only router cases`);
