import console from "node:console";
import process from "node:process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { performance } from "node:perf_hooks";
if (process.argv[2] !== "--execute" || !process.env.TYPESAFE_API_KEY) throw new Error("Use --execute with TYPESAFE_API_KEY for real development calibration.");
const root = resolve(import.meta.dirname, "..", ".."); const cases = (await readFile(resolve(root, "development/tool-router-calibration/cases.jsonl"), "utf8")).trim().split("\n").map(JSON.parse); const run = resolve(root, "development/tool-router-calibration/runs", `calibration-${new Date().toISOString().replace(/[:.]/g, "-")}`); await mkdir(run, { recursive: true });
const { ToolRouter } = await import("../../packages/core/dist/index.js"); const { TypeSafeToolRoutingJudge } = await import("../../packages/typesafe/dist/index.js"); const rows=[];
for (const item of cases) { const judge=new TypeSafeToolRoutingJudge(); const router=new ToolRouter(judge,"active"); const started=performance.now(); try { const result=await router.route(item.state,item.tools); rows.push({caseId:item.id,requiredFamilies:item.requiredFamilies,result,rawTypedOutput:judge.latestRawTypedOutput,latencyMs:Math.round(performance.now()-started)}); } catch (error) { rows.push({caseId:item.id,error:error instanceof Error?error.name:"UNKNOWN"}); } }
const families=["INSPECT","SEARCH","EDIT","EXECUTE","WEB","EXTERNAL","OTHER"]; let tp=0,fp=0,fn=0,exposed=0,required=0,exact=0; for(const r of rows){const want=new Set(r.requiredFamilies),got=new Set(r.result?.selectedFamilies??[]);for(const f of families){if(want.has(f)&&got.has(f))tp++;else if(want.has(f))fn++;else if(got.has(f))fp++;} exposed+=got.size;required+=want.size;if([...want].sort().join()===[...got].sort().join())exact++;}const precision=tp/(tp+fp||1),recall=tp/(tp+fn||1);const metrics={developmentOnly:true,cases:cases.length,realTypeSafeRequests:cases.length,providerFailures:rows.filter(r=>r.error).length,retries:0,requiredFamilyRecall:recall,requiredFamilyFNRate:fn/(required||1),setPrecision:precision,setRecall:recall,setF1:2*precision*recall/(precision+recall||1),exactSetAgreement:exact/cases.length,meanExposedFamilies:exposed/cases.length,excessExposure:fp/(exposed||1),latencyMs:rows.map(r=>r.latencyMs).sort((a,b)=>a-b)}; await writeFile(resolve(run,"raw-results.jsonl"),`${rows.map(JSON.stringify).join("\n")}\n`);await writeFile(resolve(run,"metrics.json"),`${JSON.stringify(metrics,null,2)}\n`);console.log(JSON.stringify({run,metrics}));
