/* global process */
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { validatePair } from "../runners/index.mjs";

export function median(values) { if (!values.length) return null; const sorted = [...values].sort((a, b) => a - b); const middle = Math.floor(sorted.length / 2); return sorted.length % 2 ? sorted[middle] : (sorted[middle - 1] + sorted[middle]) / 2; }
export function analyzeRuns(runs) {
  const pairs = [...new Set(runs.map((run) => run.pairId))].map((pairId) => { const pairRuns = runs.filter((run) => run.pairId === pairId); const validity = validatePair(pairRuns); const control = pairRuns.find((run) => run.arm === "control"); const treatment = pairRuns.find((run) => run.arm === "treatment"); return { pairId, ...validity, treatmentMinusControl: control && treatment ? { durationMs: treatment.durationMs - control.durationMs, toolCalls: treatment.metrics.toolCalls - control.metrics.toolCalls, failedToolCalls: treatment.metrics.failedToolCalls - control.metrics.failedToolCalls } : null }; });
  const valid = new Set(pairs.filter((pair) => pair.pairValid).map((pair) => pair.pairId));
  const summarize = (arm) => { const selected = runs.filter((run) => run.arm === arm && valid.has(run.pairId)); const number = (key) => selected.map((run) => run.metrics[key]).filter((value) => typeof value === "number"); return { n: selected.length, successRate: selected.length ? selected.filter((run) => run.metrics.taskSuccess).length / selected.length : null, medianTimeToSolutionMs: median(number("timeToSolutionMs")), medianToolCalls: median(number("toolCalls")), medianLlmTurns: median(number("llmTurns")), medianFailedToolCalls: median(number("failedToolCalls")), replanCount: selected.reduce((sum, run) => sum + run.athenaTelemetrySummary.replan, 0), reflexCompleted: selected.reduce((sum, run) => sum + run.athenaTelemetrySummary.reflexCompleted, 0), jevCalls: selected.some((run) => typeof run.athenaTelemetrySummary.jevCalls === "number") ? selected.reduce((sum, run) => sum + (run.athenaTelemetrySummary.jevCalls ?? 0), 0) : null }; };
  return { smokeTestOnly: true, validPairs: pairs.filter((pair) => pair.pairValid), invalidPairs: pairs.filter((pair) => !pair.pairValid), control: summarize("control"), treatment: summarize("treatment"), pairs };
}

const experimentId = process.argv.slice(2).find((argument) => argument !== "--");
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) { if (!experimentId) throw new Error("Usage: pnpm bench:analyze -- <experiment-id>"); const directory = join(process.cwd(), "bench", "results", experimentId); const runs = await Promise.all((await readdir(join(directory, "runs"))).filter((name) => name.endsWith(".json")).map(async (name) => JSON.parse(await readFile(join(directory, "runs", name), "utf8")))); const summary = { experimentId, ...analyzeRuns(runs) }; await writeFile(join(directory, "summary.json"), `${JSON.stringify(summary, null, 2)}\n`); await writeFile(join(directory, "summary.csv"), ["pair_id,arm,success,duration_ms,tool_calls,llm_turns,failed_tool_calls,replans,reflex_completed", ...runs.map((run) => [run.pairId, run.arm, run.metrics.taskSuccess, run.durationMs, run.metrics.toolCalls, run.metrics.llmTurns ?? "", run.metrics.failedToolCalls, run.athenaTelemetrySummary.replan, run.athenaTelemetrySummary.reflexCompleted].join(","))].join("\n") + "\n"); process.stdout.write(`${JSON.stringify(summary, null, 2)}\n`); }
