import { describe, expect, it } from "vitest";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { EventStore, saveConfig, type ReflexProvider } from "@athena/core";
import { CursorAdapter, mergeCursorHooks, runCursorHook } from "../src/index.js";
import { runAdapterComplianceSuite } from "../../agent-sdk/test/compliance.js";

const provider: ReflexProvider = { name: "demo", evaluateRisk: async () => ({ relevance: 1, unintendedChange: 0.99, broadness: 0.1, approvalNeeded: 0.1 }), evaluateProgress: async () => ({ usefulInformation: 0.1, advancedGoal: 0.1, strategyInvalidated: 0.8, continueApproach: 0.1 }), evaluateStagnation: async () => ({ sameStrategy: 0.96, sameUnderlyingProblem: 0.96, surfaceVariation: 0.9, newInformation: 0.1, likelyToProgress: 0.1, strategyChangeNeeded: 0.93 }), evaluateCompletion: async () => ({ requirementsSatisfied: 0.1, evidenceWorks: 0.1, unresolvedFailures: 0.9, testingSufficient: 0.1, shouldContinue: 0.9 }) };
async function root() { const value = await mkdtemp(join(tmpdir(), "athena-cursor-")); await saveConfig(value, { mode: "balanced", provider: "demo", reflexes: { risk: true, progress: true, stagnation: true, completion: true }, thresholds: { riskAsk: 0.8, riskDeny: 0.95, stagnation: 0.88, replan: 0.9, completionContinue: 0.85 }, telemetry: { persist: true }, budgets: { maxJevCallsPerSession: 100, minMeaningfulActionsBetweenStagnationChecks: 1, replanCooldownMeaningfulActions: 3 } }); return value; }
const input = (conversation_id: string, hook_event_name: "preToolUse" | "postToolUse" | "postToolUseFailure", tool_use_id: string, tool_name = "Shell", tool_input: unknown = { command: "pwd" }, result?: unknown) => ({ conversation_id, generation_id: "gen", hook_event_name, cursor_version: "3.19.13", model: "agent", model_id: "model-id", model_params: [{ id: "thinking", value: "high" }], cwd: "/project", tool_use_id, tool_name, tool_input, tool_output: hook_event_name === "postToolUse" ? result : undefined, error_message: hook_event_name === "postToolUseFailure" ? String(result ?? "failed") : undefined, failure_type: hook_event_name === "postToolUseFailure" ? "error" as const : undefined, duration: 24 });
runAdapterComplianceSuite(new CursorAdapter(), input("s", "preToolUse", "a"), input("s", "postToolUse", "a", "Shell", {}, { success: true }));
describe("Cursor adapter", () => {
  it("normalizes categories, model metadata, and failures", () => { const adapter = new CursorAdapter(); expect(adapter.normalizeBeforeAction(input("s", "preToolUse", "a", "MCP:db"))).toMatchObject({ category: "mcp", model: "model-id", native: { cursorVersion: "3.19.13" } }); expect(adapter.normalizeBeforeAction(input("s", "preToolUse", "b", "Grep"))).toMatchObject({ category: "search" }); expect(adapter.normalizeAfterAction(input("s", "postToolUseFailure", "a", "Shell", {}, "timeout"))).toMatchObject({ success: false, error: "timeout", durationMs: 24 }); });
  it("allows safe actions and denies deterministic danger", async () => { const value = await root(); expect(await runCursorHook(value, input("s", "preToolUse", "safe", "Read", { path: "package.json" }), provider)).toMatchObject({ permission: "allow" }); expect(await runCursorHook(value, input("s", "preToolUse", "danger", "Shell", { command: "rm -rf /" }), provider)).toMatchObject({ permission: "deny" }); });
  it("uses additional_context for one-shot replan after failures", async () => { const value = await root(); let output = {}; for (let index = 0; index < 3; index++) { const id = `a${index}`; await runCursorHook(value, input("s", "preToolUse", id, "Shell", { command: `pnpm install --retry=${index}` }), provider); output = await runCursorHook(value, input("s", "postToolUseFailure", id, "Shell", {}, "peer dependency failed"), provider); } expect(output).toEqual({}); await runCursorHook(value, input("s", "preToolUse", "next", "Read", { path: "scenario.json" }), provider); output = await runCursorHook(value, input("s", "postToolUse", "next", "Read", {}, "scenario"), provider); expect(output).toMatchObject({ additional_context: expect.stringContaining("ATHENA CONTROL") }); expect(JSON.stringify(output)).not.toMatch(/"(?:role|user_message)"/); const events = await new EventStore(join(value, ".athena", "events.jsonl")).read(); expect(events.some((event) => event.type === "REPLAN_QUEUED" && event.metadata.adapter === "cursor")).toBe(true); expect(events.some((event) => event.type === "REPLAN_CONTEXT_APPLIED")).toBe(true); });
  it("isolates sessions and redacts secrets", async () => { const value = await root(); await runCursorHook(value, input("A", "preToolUse", "a", "Shell", { token: "secret-value", command: "pwd" }), provider); await runCursorHook(value, input("B", "preToolUse", "b"), provider); const events = await new EventStore(join(value, ".athena", "events.jsonl")).read(); expect(new Set(events.map((event) => event.sessionId))).toEqual(new Set(["A", "B"])); expect(JSON.stringify(events)).not.toContain("secret-value"); });
  it("merges hooks idempotently without replacing existing matchers", () => { const source = { version: 1, hooks: { preToolUse: [{ command: "user-hook", matcher: "Shell" }] } }; const installed = mergeCursorHooks(source); expect(installed.hooks?.preToolUse?.[0]).toEqual(source.hooks.preToolUse[0]); expect(mergeCursorHooks(installed)).toEqual(installed); });
});
