import { TypeSafeClient, noul } from "@typesafe-ai/sdk";
import { AegisObserver, CognitiveAssessmentEngine, EpistemicObserver, MetisObserver, NikeObserver } from "@athena/core";
import type { AegisJudgmentInput, CompletionReflex, CompletionAssessment, CognitiveWorldState, EpistemicAssessment, EpistemicJudgmentInput, MetisJudgmentInput, NikeJudgmentInput, ProbabilisticJudge, ProgressAssessment, ProgressReflex, ReflexProvider, ReflexState, RiskReflex, SafetyAssessment, StagnationReflex, System1Snapshot } from "@athena/core";

type Answer = { noul: number };
export interface ProviderHealth { reachable: boolean; schemaValid: boolean; latencyMs?: number; error?: string }
function answers(value: unknown): Record<string, Answer> { const outer = value as { answers?: Record<string, Answer> }; if (!outer.answers || Object.values(outer.answers).some((answer) => typeof answer.noul !== "number" || answer.noul < 0 || answer.noul > 1)) throw new Error("TypeSafe returned malformed reflex response"); return outer.answers; }
function yes(response: Record<string, Answer>, key: string): number { const value = response[key]?.noul; if (typeof value !== "number" || value < 0 || value > 1) throw new Error(`TypeSafe response missing valid ${key}`); return value; }
function exactAnswers(value: unknown, keys: readonly string[]): Record<string, Answer> { const parsed = answers(value); if (Object.keys(parsed).length !== keys.length || keys.some((key) => !(key in parsed))) throw new Error("TypeSafe returned unexpected System-1 answer fields"); return parsed; }
export type TypeSafeSystem1ErrorKind = "AUTHENTICATION" | "TRANSPORT" | "TIMEOUT" | "INVALID_RESPONSE";
export class TypeSafeSystem1Error extends Error { constructor(readonly kind: TypeSafeSystem1ErrorKind) { super(`TypeSafe System-1 ${kind.toLowerCase()} failure`); this.name = "TypeSafeSystem1Error"; } }
export class TypeSafeReflexProvider implements ReflexProvider {
  readonly name = "typesafe" as const;
  private readonly client: TypeSafeClient;
  constructor(timeout = 4000, client?: TypeSafeClient) { if (!process.env.TYPESAFE_API_KEY && !client) throw new Error("TYPESAFE_API_KEY is missing"); this.client = client ?? new TypeSafeClient({ timeout }); }
  private async judge(state: ReflexState, questions: Record<string, ReturnType<typeof noul>>): Promise<Record<string, Answer>> { return answers(await this.client.systemOne({ state: JSON.stringify({ kind: "athena-reflex-state", state }), questions })); }
  async health(): Promise<ProviderHealth> { const started = performance.now(); try { const response = await this.client.systemOne({ state: { purpose: "ATHENA provider health check", safe: true }, questions: { reachable: noul("Does state indicate this is a safe provider health check?") } }); const parsed = answers(response); yes(parsed, "reachable"); return { reachable: true, schemaValid: true, latencyMs: Math.round(performance.now() - started) }; } catch (error: unknown) { return { reachable: false, schemaValid: false, latencyMs: Math.round(performance.now() - started), error: error instanceof Error ? error.message : "unknown provider failure" }; } }
  async evaluateRisk(state: ReflexState): Promise<RiskReflex> { const a = await this.judge(state, { relevance: noul("Is action meaningfully relevant to stated goal?"), unintendedChange: noul("Could action cause meaningful unintended changes?"), broadness: noul("Is action unusually broad compared with task?"), approvalNeeded: noul("Should action require human approval?") }); return { relevance: yes(a, "relevance"), unintendedChange: yes(a, "unintendedChange"), broadness: yes(a, "broadness"), approvalNeeded: yes(a, "approvalNeeded") }; }
  async evaluateProgress(state: ReflexState): Promise<ProgressReflex> { const a = await this.judge(state, { usefulInformation: noul("Did result produce useful new information?"), advancedGoal: noul("Did action materially advance goal?"), strategyInvalidated: noul("Did result invalidate current strategy?"), continueApproach: noul("Should agent keep using current approach?") }); return { usefulInformation: yes(a, "usefulInformation"), advancedGoal: yes(a, "advancedGoal"), strategyInvalidated: yes(a, "strategyInvalidated"), continueApproach: yes(a, "continueApproach") }; }
  async evaluateStagnation(state: ReflexState): Promise<StagnationReflex> { const a = await this.judge(state, { sameStrategy: noul("Do recent actions pursue essentially same underlying strategy?"), sameUnderlyingProblem: noul("Is same underlying failure unresolved across recent attempts?"), surfaceVariation: noul("Are recent actions mostly superficial variations of earlier attempts?"), newInformation: noul("Have recent results produced materially new information?"), likelyToProgress: noul("Is continuing current strategy likely to produce progress?"), strategyChangeNeeded: noul("Would changing strategy be advisable now?") }); return { sameStrategy: yes(a, "sameStrategy"), sameUnderlyingProblem: yes(a, "sameUnderlyingProblem"), surfaceVariation: yes(a, "surfaceVariation"), newInformation: yes(a, "newInformation"), likelyToProgress: yes(a, "likelyToProgress"), strategyChangeNeeded: yes(a, "strategyChangeNeeded") }; }
  async evaluateCompletion(state: ReflexState): Promise<CompletionReflex> { const a = await this.judge(state, { requirementsSatisfied: noul("Are original requirements satisfied?"), evidenceWorks: noul("Is there evidence implementation works?"), unresolvedFailures: noul("Are important unresolved failures present?"), testingSufficient: noul("Is testing sufficient for change?"), shouldContinue: noul("Should work continue?" ) }); return { requirementsSatisfied: yes(a, "requirementsSatisfied"), evidenceWorks: yes(a, "evidenceWorks"), unresolvedFailures: yes(a, "unresolvedFailures"), testingSufficient: yes(a, "testingSufficient"), shouldContinue: yes(a, "shouldContinue") }; }
}

/** Provider adapter. Core observers depend only on ProbabilisticJudge. */
export class TypeSafeSystem1Judges {
  private readonly client: TypeSafeClient;
  constructor(timeout = 4000, client?: TypeSafeClient) { if (!process.env.TYPESAFE_API_KEY && !client) throw new Error("TYPESAFE_API_KEY is missing"); this.client = client ?? new TypeSafeClient({ timeout }); }
  private async judge<Input>(kind: string, input: Input, questions: Record<string, ReturnType<typeof noul>>): Promise<Record<string, Answer>> { try { return exactAnswers(await this.client.systemOne({ state: JSON.stringify({ kind, input }), questions }), Object.keys(questions)); } catch (error) { if (error instanceof Error && error.message.startsWith("TypeSafe returned") || error instanceof Error && error.message.startsWith("TypeSafe response")) throw new TypeSafeSystem1Error("INVALID_RESPONSE"); const message = error instanceof Error ? error.message.toLowerCase() : ""; if (message.includes("timeout") || message.includes("abort")) throw new TypeSafeSystem1Error("TIMEOUT"); if (message.includes("api key") || message.includes("auth") || message.includes("unauthorized")) throw new TypeSafeSystem1Error("AUTHENTICATION"); throw new TypeSafeSystem1Error("TRANSPORT"); } }
  readonly aegis: ProbabilisticJudge<AegisJudgmentInput, SafetyAssessment> = { judge: async (input) => { const value = await this.judge("athena-aegis-perception", input, { failureProbability: noul("How likely is the candidate action to fail or produce an invalid operational result? Operational success is distinct from harmful impact."), impactSeverity: noul("If the candidate action causes the described harmful consequence, how severe could the impact be?"), irreversibility: noul("How difficult would the important described consequences be to undo?"), policyViolationProbability: noul("How likely is the candidate action to violate explicit operational constraints or safety rules in this input?") }); return { failureProbability: yes(value, "failureProbability") as SafetyAssessment["failureProbability"], impactSeverity: yes(value, "impactSeverity") as SafetyAssessment["impactSeverity"], irreversibility: yes(value, "irreversibility") as SafetyAssessment["irreversibility"], policyViolationProbability: yes(value, "policyViolationProbability") as SafetyAssessment["policyViolationProbability"] }; } };
  readonly metis: ProbabilisticJudge<MetisJudgmentInput, ProgressAssessment> = { judge: async (input) => { const value = await this.judge("athena-metis-perception", input, { progressProbability: noul("How likely is candidate to materially advance explicit goal?"), informationGainProbability: noul("How likely is candidate to yield useful evidence?"), strategyNovelty: noul("How materially different is candidate strategy from recent strategies?"), stagnationProbability: noul("How likely is agent persisting in exhausted strategy without enough new information?"), goalAlignment: noul("How aligned is candidate with explicit goal?") }); return { progressProbability: yes(value, "progressProbability") as ProgressAssessment["progressProbability"], informationGainProbability: yes(value, "informationGainProbability") as ProgressAssessment["informationGainProbability"], strategyNovelty: yes(value, "strategyNovelty") as ProgressAssessment["strategyNovelty"], stagnationProbability: yes(value, "stagnationProbability") as ProgressAssessment["stagnationProbability"], goalAlignment: yes(value, "goalAlignment") as ProgressAssessment["goalAlignment"] }; } };
  readonly nike: ProbabilisticJudge<NikeJudgmentInput, CompletionAssessment> = { judge: async (input) => { const value = await this.judge("athena-nike-perception", input, { goalSatisfiedProbability: noul("Given the available evidence, how likely is the explicit task goal itself actually satisfied? A complete candidate means completion is being claimed, not that it is true."), evidenceCoverage: noul("How completely does current observation and action evidence support the goal requirements and acceptance criteria needed to claim completion?"), unresolvedObligationsProbability: noul("How likely is it that meaningful requirements, checks, or listed obligations remain unresolved, considering each obligation status?") }); return { goalSatisfiedProbability: yes(value, "goalSatisfiedProbability") as CompletionAssessment["goalSatisfiedProbability"], evidenceCoverage: yes(value, "evidenceCoverage") as CompletionAssessment["evidenceCoverage"], unresolvedObligationsProbability: yes(value, "unresolvedObligationsProbability") as CompletionAssessment["unresolvedObligationsProbability"] }; } };
  readonly epistemic: ProbabilisticJudge<EpistemicJudgmentInput, EpistemicAssessment> = { judge: async (input) => { const value = await this.judge("athena-epistemic-perception", input, { stateUncertainty: noul("How uncertain is the relevant current task or environment state from this evidence?"), contextSufficiency: noul("Does this compact goal, candidate, observation, action, strategy, and obligation evidence contain enough context to make a meaningful cognitive judgment, even if it cannot solve the task?"), contradictionProbability: noul("How likely do current observation, recent action evidence, strategies, obligations, or task claims materially conflict?") }); return { stateUncertainty: yes(value, "stateUncertainty") as EpistemicAssessment["stateUncertainty"], contextSufficiency: yes(value, "contextSufficiency") as EpistemicAssessment["contextSufficiency"], contradictionProbability: yes(value, "contradictionProbability") as EpistemicAssessment["contradictionProbability"] }; } };
}

export class TypeSafeSystem1Runtime {
  readonly judges: TypeSafeSystem1Judges;
  readonly engine: CognitiveAssessmentEngine;
  constructor(timeout = 4000, client?: TypeSafeClient) { this.judges = new TypeSafeSystem1Judges(timeout, client); this.engine = new CognitiveAssessmentEngine({ aegis: new AegisObserver(this.judges.aegis), metis: new MetisObserver(this.judges.metis), nike: new NikeObserver(this.judges.nike), epistemic: new EpistemicObserver(this.judges.epistemic) }); }
  assess(world: CognitiveWorldState): Promise<System1Snapshot> { return this.engine.snapshot(world); }
}

export function createTypeSafeSystem1(timeout = 4000, client?: TypeSafeClient): TypeSafeSystem1Runtime { return new TypeSafeSystem1Runtime(timeout, client); }
export class DemoReflexProvider implements ReflexProvider {
  readonly name = "demo" as const;
  async evaluateRisk(state: ReflexState): Promise<RiskReflex> { const text = state.action?.input.toLowerCase() ?? ""; const risky = /rm -rf|reset --hard|drop table/.test(text); return { relevance: 0.96, unintendedChange: risky ? 0.99 : 0.18, broadness: risky ? 0.98 : 0.12, approvalNeeded: risky ? 0.99 : 0.05 }; }
  async evaluateProgress(state: ReflexState): Promise<ProgressReflex> { return { usefulInformation: state.result?.success ? 0.8 : 0.1, advancedGoal: state.result?.success ? 0.75 : 0.15, strategyInvalidated: state.result?.success ? 0.1 : 0.8, continueApproach: state.result?.success ? 0.8 : 0.2 }; }
  async evaluateStagnation(state: ReflexState): Promise<StagnationReflex> { const strategies = state.recentActions.map((action) => action.strategy); const repeating = strategies.length >= 3 && new Set(strategies).size <= 1; return { sameStrategy: repeating ? 0.96 : 0.12, sameUnderlyingProblem: repeating ? 0.94 : 0.18, surfaceVariation: repeating ? 0.9 : 0.12, newInformation: repeating ? 0.08 : 0.72, likelyToProgress: repeating ? 0.1 : 0.78, strategyChangeNeeded: repeating ? 0.93 : 0.08 }; }
  async evaluateCompletion(state: ReflexState): Promise<CompletionReflex> { const failed = state.buildStatus === "failed" || state.testStatus === "failed" || state.currentErrors.length > 0; const untested = state.buildStatus === "unknown" || state.testStatus === "unknown"; return { requirementsSatisfied: failed ? 0.35 : 0.9, evidenceWorks: failed ? 0.3 : 0.9, unresolvedFailures: failed ? 0.9 : 0.05, testingSufficient: untested ? 0.25 : 0.9, shouldContinue: failed || untested ? 0.93 : 0.08 }; }
}

export { type System2ModelConfig, type System2Fetch, type System2FetchResponse, System2ProviderError, system2ModelConfigFromEnvironment, OpenAICompatibleSystem2Bridge } from "./system2.js";
