import { CognitivePolicy, System2DeliberationOrchestrator, buildCognitiveWorldState, initialCognitiveState, policyResultToDecisionEvent, policyResultToEvidenceEvent, transitionCognitiveState } from "@athena/core";
import { createTypeSafeSystem1 } from "./index.js";
import { OpenAICompatibleSystem2Bridge, system2ModelConfigFromEnvironment } from "./system2.js";

const world = buildCognitiveWorldState({ goal: { goalId: "auth-expiry", description: "Fix authentication sessions expiring thirty minutes early", acceptanceCriteria: ["Session remains valid until configured expiration", "Authentication expiry test passes"] }, candidate: { id: "stagnation", kind: "tool", tool: "test", intent: "rerun authentication expiry test with same configuration" }, currentObservation: { source: "authentication expiry test", summary: "Test still reports session expired thirty minutes early after repeated reruns.", outcome: "FAILURE", errorSummary: "Expected valid session; received expired token." }, recentActions: [{ candidateId: "s1", kind: "tool", intent: "rerun authentication expiry test", outcome: "FAILURE", informationSummary: "Same early expiration failure." }, { candidateId: "s2", kind: "tool", intent: "rerun expiry test with verbose output", outcome: "FAILURE", informationSummary: "Same failure; no new failing location." }, { candidateId: "s3", kind: "tool", intent: "rerun authentication expiry test", outcome: "FAILURE", informationSummary: "Same early expiration failure." }], recentStrategies: [{ strategyId: "rerun-expiry-test", intent: "fix early expiration", approach: "rerun authentication expiry test", hypothesisId: "test-flake", target: "AuthExpiryTest" }, { strategyId: "rerun-expiry-test", intent: "fix early expiration", approach: "rerun authentication expiry test", hypothesisId: "test-flake", target: "AuthExpiryTest" }, { strategyId: "rerun-expiry-test", intent: "fix early expiration", approach: "rerun authentication expiry test", hypothesisId: "test-flake", target: "AuthExpiryTest" }], unresolvedObligations: [{ id: "expiry-root-cause", description: "Identify early expiration calculation", status: "OPEN" }, { id: "expiry-test", description: "Pass authentication expiry test", status: "OPEN" }], environment: { workingMode: "live-dual", availableCapabilities: ["read", "test"], relevantConstraints: ["Do not weaken authentication expiration", "Preserve configured session duration"] } });
const model = system2ModelConfigFromEnvironment();
const snapshot = await createTypeSafeSystem1().assess(world);
const policy = new CognitivePolicy().evaluate(snapshot.assessment, { ...initialCognitiveState(), consecutiveLowProgress: 2, consecutiveLowInformationGain: 2, consecutiveHighStagnation: 2 }, world);
if (policy.decision !== "DELIBERATE") { process.stdout.write(`${JSON.stringify({ decision: policy.decision, reasons: policy.reasons })}\n`); process.exit(0); }
let state = transitionCognitiveState({ ...initialCognitiveState(), consecutiveLowProgress: 2, consecutiveLowInformationGain: 2, consecutiveHighStagnation: 2 }, { type: "CANDIDATE_PROPOSED", candidateId: world.candidate.id, kind: world.candidate.kind, intent: world.candidate.intent, timestamp: "live", sessionId: "dual" });
state = transitionCognitiveState(state, { type: "ASSESSMENT_STARTED", candidateId: world.candidate.id, timestamp: "live", sessionId: "dual" });
state = transitionCognitiveState(state, { type: "ASSESSMENT_COMPLETED", candidateId: world.candidate.id, assessment: snapshot.assessment, timestamp: "live", sessionId: "dual" });
state = transitionCognitiveState(state, policyResultToEvidenceEvent(policy, world.candidate.id, "live", "dual"));
state = transitionCognitiveState(state, policyResultToDecisionEvent(policy, snapshot.assessment, world.candidate.id, "live", "dual"));
const output = await new System2DeliberationOrchestrator(new OpenAICompatibleSystem2Bridge(model)).deliberate({ requestId: "live-dual", policy, world, assessment: snapshot.assessment, state, sessionId: "dual", timestamp: "live", currentState: () => state });
state = transitionCognitiveState(state, output.events[0]);
state = transitionCognitiveState(state, output.events[1]);
if (output.strategyShift.strategyChanged) state = transitionCognitiveState(state, { type: "STRATEGY_SHIFT_OBSERVED", candidateId: world.candidate.id, from: output.request.currentStrategy.strategyId, to: output.revisedStrategy.strategyId, timestamp: "live", sessionId: "dual" });
process.stdout.write(`${JSON.stringify({ model: model.model, decision: policy.decision, reasons: policy.reasons, oldStrategy: output.request.currentStrategy, revisedStrategy: output.revisedStrategy, strategyShift: output.strategyShift, lifecycle: state.phase, nextCandidateRequiresSystem1: true })}\n`);
