import { assessStrategyShift, buildCognitiveWorldState, buildDeliberationRequest, type CognitiveAssessment, type CognitivePolicyResult } from "@athena/core";
import { OpenAICompatibleSystem2Bridge, system2ModelConfigFromEnvironment } from "./system2.js";

const policy: CognitivePolicyResult = { decision: "DELIBERATE", reasons: ["PERSISTENT_STAGNATION"], policyVersion: "0.3.0", triggeredRules: ["persistent-stagnation"], temporalEvidence: { consecutiveLowProgress: 3, consecutiveLowInformationGain: 3, consecutiveHighStagnation: 3 } };
const assessment = { safety: { failureProbability: 0.1, impactSeverity: 0.1, irreversibility: 0.1, policyViolationProbability: 0.1 }, progress: { progressProbability: 0.1, informationGainProbability: 0.1, strategyNovelty: 0.1, stagnationProbability: 0.9, goalAlignment: 0.9 }, completion: { goalSatisfiedProbability: 0.1, evidenceCoverage: 0.1, unresolvedObligationsProbability: 0.9 }, epistemics: { stateUncertainty: 0.2, contextSufficiency: 0.9, contradictionProbability: 0.1 } } as unknown as CognitiveAssessment;
const world = { goal: { goalId: "defect", description: "Identify and fix underlying authentication defect", acceptanceCriteria: ["Authentication test passes"] }, candidate: { id: "candidate", kind: "tool" as const, tool: "test", intent: "rerun same failing authentication test" }, currentObservation: { source: "test", summary: "Same authentication failure repeated without new information", outcome: "FAILURE" as const }, recentActions: [{ candidateId: "a1", kind: "tool" as const, intent: "rerun failing authentication test", outcome: "FAILURE" as const }, { candidateId: "a2", kind: "tool" as const, intent: "rerun failing authentication test", outcome: "FAILURE" as const }], recentStrategies: [{ strategyId: "rerun-test", intent: "fix authentication", approach: "rerun failing test", hypothesisId: "test-flake" }], unresolvedObligations: [{ id: "root-cause", description: "Identify root cause", status: "OPEN" as const }], environment: { workingMode: "live-smoke", availableCapabilities: ["read", "test"], relevantConstraints: ["Preserve authentication security"] } };
const request = buildDeliberationRequest("live-system2", policy, buildCognitiveWorldState(world), assessment);
const config = system2ModelConfigFromEnvironment();
const result = await new OpenAICompatibleSystem2Bridge(config).deliberate(request);
const shift = assessStrategyShift(request.currentStrategy, result.revisedStrategy);
process.stdout.write(`${JSON.stringify({ model: config.model, failureMode: request.failureMode, oldStrategy: request.currentStrategy, revisedStrategy: result.revisedStrategy, strategyShift: shift, candidateAction: result.candidateAction ?? null })}\n`);
