import { createHash, randomUUID } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { EventStore, createSession, decide, isMeaningful, loadConfig, redact, stagnationEligible, stateFor, stagnationScore, strategyFamily, type Action, type PendingReplan, type ReflexProvider, type Session, type ToolResult } from "@athena/core";
import { DemoReflexProvider, TypeSafeReflexProvider } from "@athena/typesafe";
import type { AgentAction, AgentActionCategory, AgentActionResult, AgentCapabilities, AthenaAgentAdapter, AthenaControlSignal } from "@athena/agent-sdk";

export const CONTROL_INSTRUCTION = "ATHENA CONTROL\n\nThe current strategy is semantically stagnant.\nStop retrying superficial variations of the same approach.\nUse the evidence already collected to reassess the unresolved root cause.\nChoose a materially different strategy before the next meaningful action.";
export type CursorHookEvent = "preToolUse" | "postToolUse" | "postToolUseFailure";
export interface CursorHookInput { conversation_id: string; generation_id?: string; hook_event_name: CursorHookEvent; cursor_version?: string; model?: string; model_id?: string; model_params?: unknown; tool_name: string; tool_input: unknown; tool_use_id: string; cwd: string; tool_output?: unknown; error_message?: string; failure_type?: "timeout" | "error" | "permission_denied"; duration?: number; [key: string]: unknown }
export interface CursorHookOutput { permission?: "allow" | "deny"; agent_message?: string; additional_context?: string; updated_input?: unknown }
export interface CursorHooksConfig { version?: number; hooks?: Record<string, Array<{ command: string; matcher?: string }>> }

export function mergeCursorHooks(config: CursorHooksConfig, command = "athena hook cursor"): CursorHooksConfig { const hooks = { ...(config.hooks ?? {}) }; for (const event of ["preToolUse", "postToolUse", "postToolUseFailure"] as const) { const list = [...(hooks[event] ?? [])]; const hookCommand = `${command} ${event}`; if (!list.some((hook) => hook.command === hookCommand)) list.push({ command: hookCommand }); hooks[event] = list; } return { ...config, version: config.version ?? 1, hooks }; }
function category(tool: string): AgentActionCategory { const name = tool.toLowerCase(); if (name === "shell") return "shell"; if (name === "read") return "read"; if (name === "write") return "write"; if (/edit/.test(name)) return "edit"; if (/delete/.test(name)) return "delete"; if (/grep|search|glob/.test(name)) return "search"; if (/^mcp:/.test(name)) return "mcp"; if (/task/.test(name)) return "subagent"; return "other"; }
function redactedJson(value: unknown): string { return redact(JSON.stringify(value)).replace(/("(?:api[_-]?key|password|token|secret)"\s*:\s*")[^"]*/gi, "$1[REDACTED]"); }

export class CursorAdapter implements AthenaAgentAdapter<CursorHookInput, CursorHookInput, CursorHookOutput> {
  readonly id = "cursor";
  readonly runtime = "cursor";
  // Cursor documents additional_context as conversation context, not a user message. Failure hooks have no output channel.
  readonly capabilities: AgentCapabilities = { beforeAction: true, afterAction: true, denyAction: true, modifyAction: true, privilegedContextInjection: true, completionObservation: false, completionControl: false, compactionObservation: false, nativeUI: false };
  normalizeBeforeAction(input: CursorHookInput): AgentAction { return { id: input.tool_use_id, sessionId: input.conversation_id, runtime: this.runtime, model: input.model_id ?? input.model, tool: input.tool_name, category: category(input.tool_name), input: input.tool_input, cwd: input.cwd, timestamp: new Date().toISOString(), native: { generationId: input.generation_id, model: input.model, modelId: input.model_id, modelParams: input.model_params, cursorVersion: input.cursor_version, agentMessage: input.agent_message } }; }
  normalizeAfterAction(input: CursorHookInput): AgentActionResult { const failure = input.hook_event_name === "postToolUseFailure"; return { actionId: input.tool_use_id, sessionId: input.conversation_id, success: !failure, result: failure ? input.error_message ?? "tool failed" : input.tool_output, error: failure ? input.error_message : undefined, durationMs: input.duration, timestamp: new Date().toISOString(), native: { failureType: input.failure_type, generationId: input.generation_id } }; }
  encodeControl(signal: AthenaControlSignal, reason = "", context = ""): CursorHookOutput { if (signal === "DENY") return { permission: "deny", agent_message: reason || "ATHENA policy denied this action" }; if (signal === "ALLOW") return { permission: "allow" }; if (signal === "REPLAN") return { additional_context: context || CONTROL_INSTRUCTION }; return {}; }
}

interface StoredState { session: Session; actions: Record<string, Action>; replans: Record<string, PendingReplan> }
async function statePath(root: string, session: string) { const dir = join(root, ".athena", "cursor"); await mkdir(dir, { recursive: true }); return join(dir, `${createHash("sha256").update(session).digest("hex")}.json`); }
async function readState(root: string, session: string): Promise<StoredState> { try { return JSON.parse(await readFile(await statePath(root, session), "utf8")) as StoredState; } catch { return { session: createSession("Cursor session"), actions: {}, replans: {} }; } }
async function saveState(root: string, session: string, state: StoredState) { await writeFile(await statePath(root, session), JSON.stringify(state)); }
function providerFor(name: "typesafe" | "demo"): ReflexProvider { return name === "demo" ? new DemoReflexProvider() : new TypeSafeReflexProvider(); }

export async function runCursorHook(root: string, input: CursorHookInput, provider?: ReflexProvider): Promise<CursorHookOutput> {
  const adapter = new CursorAdapter(); const config = await loadConfig(root); const current = await readState(root, input.conversation_id); const reflexProvider = provider ?? providerFor(config.provider); const store = new EventStore(join(root, ".athena", "events.jsonl"), config.telemetry.persist); const metadata = { adapter: "cursor", runtime: "cursor", runtimeVersion: input.cursor_version, model: input.model_id ?? input.model };
  const evaluate = async <T>(kind: "risk" | "progress" | "stagnation", run: () => Promise<T>) => { if (current.session.jevCalls >= config.budgets.maxJevCallsPerSession) return undefined; await store.append({ timestamp: new Date().toISOString(), sessionId: input.conversation_id, type: "REFLEX_STARTED", metadata: { ...metadata, reflex: kind } }); try { const value = await run(); current.session.jevCalls++; await store.append({ timestamp: new Date().toISOString(), sessionId: input.conversation_id, type: "REFLEX_COMPLETED", metadata: { ...metadata, reflex: kind, scores: value } }); return value; } catch (error) { await store.append({ timestamp: new Date().toISOString(), sessionId: input.conversation_id, type: "REFLEX_FAILED", metadata: { ...metadata, reflex: kind, error: error instanceof Error ? error.message : "provider failure" } }); return undefined; } };
  if (input.hook_event_name === "preToolUse") { const normalized = adapter.normalizeBeforeAction(input); const action: Action = { id: normalized.id, tool: normalized.tool, input: redactedJson(normalized.input), readOnly: normalized.category === "read" || normalized.category === "search", timestamp: normalized.timestamp }; current.session.actions.push(action); current.actions[action.id] = action; if (isMeaningful(action)) current.session.meaningfulActions++; await store.append({ timestamp: action.timestamp, sessionId: input.conversation_id, type: "ACTION_PROPOSED", metadata: { ...metadata, action: { ...normalized, input: action.input } } }); const risk = !action.readOnly && config.reflexes.risk ? await evaluate("risk", () => reflexProvider.evaluateRisk(stateFor(current.session, action))) : undefined; const policy = decide(config, { action, risk }); await store.append({ timestamp: new Date().toISOString(), sessionId: input.conversation_id, type: policy.decision === "deny" ? "ACTION_DENIED" : policy.decision === "ask" ? "ACTION_ASKED" : "ACTION_ALLOWED", metadata: { ...metadata, ...policy } }); await saveState(root, input.conversation_id, current); return policy.decision === "deny" && !policy.shadow ? adapter.encodeControl("DENY", policy.reason) : adapter.encodeControl("ALLOW"); }
  const normalized = adapter.normalizeAfterAction(input); const action = current.actions[normalized.actionId]; if (!action) return {}; const result: ToolResult = { actionId: action.id, success: normalized.success, output: redactedJson(normalized.result), timestamp: normalized.timestamp }; current.session.results.push(result); await store.append({ timestamp: result.timestamp, sessionId: input.conversation_id, type: result.success ? "TOOL_COMPLETED" : "TOOL_FAILED", metadata: { ...metadata, failureType: input.failure_type } }); const state = stateFor(current.session, action, result); if (config.reflexes.progress && isMeaningful(action)) await evaluate("progress", () => reflexProvider.evaluateProgress(state)); const stagnation = config.reflexes.stagnation && stagnationEligible(current.session, config) ? await evaluate("stagnation", () => reflexProvider.evaluateStagnation(state)) : undefined; const policy = decide(config, { action, stagnation }); let output: CursorHookOutput = {};
  const pending = current.replans[input.conversation_id]; if (pending?.state === "queued" && input.hook_event_name === "postToolUse") { pending.consumed = true; pending.state = "injected"; await store.append({ timestamp: new Date().toISOString(), sessionId: input.conversation_id, type: "REPLAN_CONTEXT_APPLIED", metadata: { ...metadata, replanId: pending.id, context: "additional_context" } }); output = adapter.encodeControl("REPLAN", "semantic stagnation", CONTROL_INSTRUCTION); } else if (pending?.state === "injected" && isMeaningful(action)) { pending.state = "resolved"; pending.outcome = strategyFamily(action) === strategyFamily(current.session.actions.at(-2) ?? action) ? "ignored" : "changed"; await store.append({ timestamp: new Date().toISOString(), sessionId: input.conversation_id, type: "POST_REPLAN_ACTION", metadata: { ...metadata, replanId: pending.id, tool: action.tool } }); await store.append({ timestamp: new Date().toISOString(), sessionId: input.conversation_id, type: "REPLAN_OUTCOME", metadata: { ...metadata, replanId: pending.id, outcome: pending.outcome } }); }
  if (stagnation && policy.decision === "replan" && !policy.shadow && !pending) { const replan: PendingReplan = { id: `replan_${randomUUID().slice(0, 12)}`, sessionID: input.conversation_id, createdAt: Date.now(), stagnationScore: stagnationScore(stagnation), evidence: stagnation, consumed: input.hook_event_name === "postToolUse", state: input.hook_event_name === "postToolUse" ? "injected" : "queued" }; current.replans[input.conversation_id] = replan; current.session.replans++; current.session.lastReplanMeaningfulAction = current.session.meaningfulActions; await store.append({ timestamp: new Date().toISOString(), sessionId: input.conversation_id, type: "REPLAN_QUEUED", metadata: { ...metadata, replanId: replan.id, stagnationScore: replan.stagnationScore } }); if (input.hook_event_name === "postToolUse") { await store.append({ timestamp: new Date().toISOString(), sessionId: input.conversation_id, type: "REPLAN_CONTEXT_APPLIED", metadata: { ...metadata, replanId: replan.id, context: "additional_context" } }); output = adapter.encodeControl("REPLAN", "semantic stagnation", CONTROL_INSTRUCTION); } }
  await saveState(root, input.conversation_id, current); return output;
}
