import { createHash, randomUUID } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { EventStore, createSession, decide, isMeaningful, loadConfig, redact, stagnationEligible, stateFor, stagnationScore, strategyFamily, type Action, type PendingReplan, type ReflexProvider, type Session, type ToolResult } from "@athena/core";
import { DemoReflexProvider, TypeSafeReflexProvider } from "@athena/typesafe";
import type { AgentAction, AgentActionCategory, AgentActionResult, AgentCapabilities, AthenaAgentAdapter, AthenaControlSignal } from "@athena/agent-sdk";

export const CONTROL_INSTRUCTION = "ATHENA CONTROL\n\nThe current strategy is semantically stagnant.\nStop retrying superficial variations of the same approach.\nUse the evidence already collected to reassess the unresolved root cause.\nChoose a materially different strategy before the next meaningful action.";
export interface CodexHookInput { session_id: string; turn_id: string; cwd: string; hook_event_name: "PreToolUse" | "PostToolUse"; model?: string; tool_name: string; tool_input: unknown; tool_response?: unknown; tool_use_id: string; [key: string]: unknown }
export interface CodexHookOutput { hookSpecificOutput?: { hookEventName: "PreToolUse" | "PostToolUse"; permissionDecision?: "deny"; permissionDecisionReason?: string; additionalContext?: string } }
export interface CodexHooksConfig { description?: string; hooks?: Record<string, Array<{ matcher?: string; hooks: Array<{ type: string; command: string; timeout?: number }> }>> }

export function mergeCodexHooks(config: CodexHooksConfig, command = "athena hook codex"): CodexHooksConfig { const hooks = { ...(config.hooks ?? {}) }; for (const event of ["PreToolUse", "PostToolUse"]) { const groups = [...(hooks[event] ?? [])]; const hookCommand = `${command} ${event}`; if (!groups.some((group) => group.hooks.some((hook) => hook.type === "command" && hook.command === hookCommand))) groups.push({ hooks: [{ type: "command", command: hookCommand, timeout: 30 }] }); hooks[event] = groups; } return { ...config, hooks }; }

function category(tool: string): AgentActionCategory { const name = tool.toLowerCase(); if (/bash|shell|command/.test(name)) return "shell"; if (/read|view/.test(name)) return "read"; if (/write|create/.test(name)) return "write"; if (/edit|patch/.test(name)) return "edit"; if (/delete|remove/.test(name)) return "delete"; if (/search|grep|glob/.test(name)) return "search"; if (/mcp/.test(name)) return "mcp"; if (/agent|subagent/.test(name)) return "subagent"; if (/web|fetch|network/.test(name)) return "network"; return "other"; }
function text(value: unknown): string { return typeof value === "string" ? value : JSON.stringify(value ?? ""); }
function redactedJson(value: unknown): string { return redact(JSON.stringify(value)).replace(/("(?:api[_-]?key|password|token|secret)"\s*:\s*")[^"]*/gi, "$1[REDACTED]"); }
function success(response: unknown): boolean { if (typeof response !== "object" || response === null) return true; const item = response as Record<string, unknown>; return item.success !== false && item.error === undefined && item.exit_code !== "1" && item.exitCode !== 1; }

export class CodexAdapter implements AthenaAgentAdapter<CodexHookInput, CodexHookInput, CodexHookOutput> {
  readonly id = "codex";
  readonly runtime = "codex";
  readonly capabilities: AgentCapabilities = { beforeAction: true, afterAction: true, denyAction: true, modifyAction: false, privilegedContextInjection: true, completionObservation: false, completionControl: false, compactionObservation: true, nativeUI: false };
  normalizeBeforeAction(input: CodexHookInput): AgentAction { return { id: input.tool_use_id, sessionId: input.session_id, runtime: this.runtime, model: input.model, tool: input.tool_name, category: category(input.tool_name), input: input.tool_input, cwd: input.cwd, timestamp: new Date().toISOString(), native: { turnId: input.turn_id, agentId: input.agent_id, permissionMode: input.permission_mode } }; }
  normalizeAfterAction(input: CodexHookInput): AgentActionResult { const response = input.tool_response; const item = response && typeof response === "object" ? response as Record<string, unknown> : {}; const exitCode = typeof item.exit_code === "number" ? item.exit_code : typeof item.exitCode === "number" ? item.exitCode : undefined; const error = typeof item.error === "string" ? item.error : undefined; return { actionId: input.tool_use_id, sessionId: input.session_id, success: success(response), exitCode, result: response, error, timestamp: new Date().toISOString(), native: { turnId: input.turn_id } }; }
  encodeControl(signal: AthenaControlSignal, reason = "", context = ""): CodexHookOutput { if (signal === "DENY") return { hookSpecificOutput: { hookEventName: "PreToolUse", permissionDecision: "deny", permissionDecisionReason: reason || "ATHENA policy denied this action" } }; if (signal === "REPLAN") return { hookSpecificOutput: { hookEventName: "PostToolUse", additionalContext: context || CONTROL_INSTRUCTION } }; return {}; }
}

interface StoredState { session: Session; actions: Record<string, Action>; replans: Record<string, PendingReplan> }
async function statePath(root: string, sessionId: string) { const safe = createHash("sha256").update(sessionId).digest("hex"); const dir = join(root, ".athena", "codex"); await mkdir(dir, { recursive: true }); return join(dir, `${safe}.json`); }
async function readState(root: string, sessionId: string): Promise<StoredState> { try { return JSON.parse(await readFile(await statePath(root, sessionId), "utf8")) as StoredState; } catch { return { session: createSession("Codex session"), actions: {}, replans: {} }; } }
async function saveState(root: string, sessionId: string, state: StoredState) { await writeFile(await statePath(root, sessionId), JSON.stringify(state)); }
function providerFor(name: "typesafe" | "demo"): ReflexProvider { return name === "demo" ? new DemoReflexProvider() : new TypeSafeReflexProvider(); }

export async function runCodexHook(root: string, input: CodexHookInput, provider?: ReflexProvider): Promise<CodexHookOutput> {
  const adapter = new CodexAdapter(); const config = await loadConfig(root); const current = await readState(root, input.session_id); const reflexProvider = provider ?? providerFor(config.provider); const store = new EventStore(join(root, ".athena", "events.jsonl"), config.telemetry.persist); const metadata = { adapter: "codex", runtime: "codex", model: input.model, runtimeVersion: process.env.CODEX_VERSION };
  const evaluate = async <T>(kind: "risk" | "progress" | "stagnation", run: () => Promise<T>) => { if (current.session.jevCalls >= config.budgets.maxJevCallsPerSession) return undefined; await store.append({ timestamp: new Date().toISOString(), sessionId: input.session_id, type: "REFLEX_STARTED", metadata: { ...metadata, reflex: kind } }); try { const value = await run(); current.session.jevCalls++; await store.append({ timestamp: new Date().toISOString(), sessionId: input.session_id, type: "REFLEX_COMPLETED", metadata: { ...metadata, reflex: kind, scores: value } }); return value; } catch (error) { await store.append({ timestamp: new Date().toISOString(), sessionId: input.session_id, type: "REFLEX_FAILED", metadata: { ...metadata, reflex: kind, error: error instanceof Error ? error.message : "provider failure" } }); return undefined; } };
  if (input.hook_event_name === "PreToolUse") { const normalized = adapter.normalizeBeforeAction(input); const redactedInput = redactedJson(normalized.input); const action: Action = { id: normalized.id, tool: normalized.tool, input: redactedInput, readOnly: normalized.category === "read" || normalized.category === "search", timestamp: normalized.timestamp }; current.session.actions.push(action); current.actions[action.id] = action; if (isMeaningful(action)) current.session.meaningfulActions++; await store.append({ timestamp: action.timestamp, sessionId: input.session_id, type: "ACTION_PROPOSED", metadata: { ...metadata, action: { ...normalized, input: redactedInput } } }); const risk = !action.readOnly && config.reflexes.risk ? await evaluate("risk", () => reflexProvider.evaluateRisk(stateFor(current.session, action))) : undefined; const policy = decide(config, { action, risk }); await store.append({ timestamp: new Date().toISOString(), sessionId: input.session_id, type: policy.decision === "deny" ? "ACTION_DENIED" : policy.decision === "ask" ? "ACTION_ASKED" : "ACTION_ALLOWED", metadata: { ...metadata, ...policy } }); await saveState(root, input.session_id, current); return policy.decision === "deny" && !policy.shadow ? adapter.encodeControl("DENY", policy.reason) : {}; }
  const normalized = adapter.normalizeAfterAction(input); const action = current.actions[normalized.actionId]; if (!action) return {}; const result: ToolResult = { actionId: action.id, success: normalized.success, output: text(normalized.result), changedFiles: normalized.changedFiles, timestamp: normalized.timestamp }; current.session.results.push(result); await store.append({ timestamp: result.timestamp, sessionId: input.session_id, type: result.success ? "TOOL_COMPLETED" : "TOOL_FAILED", metadata }); const state = stateFor(current.session, action, result); if (config.reflexes.progress && isMeaningful(action)) await evaluate("progress", () => reflexProvider.evaluateProgress(state)); const stagnation = config.reflexes.stagnation && stagnationEligible(current.session, config) ? await evaluate("stagnation", () => reflexProvider.evaluateStagnation(state)) : undefined; const policy = decide(config, { action, stagnation }); let output: CodexHookOutput = {};
  const pending = current.replans[input.session_id]; if (pending?.state === "injected" && isMeaningful(action)) { pending.state = "resolved"; pending.outcome = strategyFamily(action) === strategyFamily(current.session.actions.at(-2) ?? action) ? "ignored" : "changed"; await store.append({ timestamp: new Date().toISOString(), sessionId: input.session_id, type: "POST_REPLAN_ACTION", metadata: { ...metadata, replanId: pending.id, tool: action.tool } }); await store.append({ timestamp: new Date().toISOString(), sessionId: input.session_id, type: "REPLAN_OUTCOME", metadata: { ...metadata, replanId: pending.id, outcome: pending.outcome } }); }
  if (stagnation && policy.decision === "replan" && !policy.shadow && !current.replans[input.session_id]) { const replan: PendingReplan = { id: `replan_${randomUUID().slice(0, 12)}`, sessionID: input.session_id, createdAt: Date.now(), stagnationScore: stagnationScore(stagnation), evidence: stagnation, consumed: true, state: "injected", instructionHash: createHash("sha256").update(CONTROL_INSTRUCTION).digest("hex").slice(0, 16) }; current.replans[input.session_id] = replan; current.session.replans++; current.session.lastReplanMeaningfulAction = current.session.meaningfulActions; await store.append({ timestamp: new Date().toISOString(), sessionId: input.session_id, type: "REPLAN_QUEUED", metadata: { ...metadata, replanId: replan.id, stagnationScore: replan.stagnationScore } }); await store.append({ timestamp: new Date().toISOString(), sessionId: input.session_id, type: "REPLAN_CONTEXT_APPLIED", metadata: { ...metadata, replanId: replan.id, context: "developer" } }); output = adapter.encodeControl("REPLAN", "semantic stagnation", CONTROL_INSTRUCTION); }
  await saveState(root, input.session_id, current); return output;
}
