import { describe, expect, it } from "vitest";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { EventStore, saveConfig, type ReflexProvider } from "@athena/core";
import { CodexAdapter, mergeCodexHooks, runCodexHook } from "../src/index.js";
import { runAdapterComplianceSuite } from "../../agent-sdk/test/compliance.js";

const provider: ReflexProvider = { name: "demo", evaluateRisk: async () => ({ relevance: 1, unintendedChange: 0.99, broadness: 0.1, approvalNeeded: 0.1 }), evaluateProgress: async () => ({ usefulInformation: 0.1, advancedGoal: 0.1, strategyInvalidated: 0.8, continueApproach: 0.1 }), evaluateStagnation: async () => ({ sameStrategy: 0.96, sameUnderlyingProblem: 0.96, surfaceVariation: 0.9, newInformation: 0.1, likelyToProgress: 0.1, strategyChangeNeeded: 0.93 }), evaluateCompletion: async () => ({ requirementsSatisfied: 0.1, evidenceWorks: 0.1, unresolvedFailures: 0.9, testingSufficient: 0.1, shouldContinue: 0.9 }) };
async function root() { const value = await mkdtemp(join(tmpdir(), "athena-codex-")); await saveConfig(value, { mode: "balanced", provider: "demo", reflexes: { risk: true, progress: true, stagnation: true, completion: true }, thresholds: { riskAsk: 0.8, riskDeny: 0.95, stagnation: 0.88, replan: 0.9, completionContinue: 0.85 }, telemetry: { persist: true }, budgets: { maxJevCallsPerSession: 100, minMeaningfulActionsBetweenStagnationChecks: 1, replanCooldownMeaningfulActions: 3 } }); return value; }
const input = (session_id: string, hook_event_name: "PreToolUse" | "PostToolUse", tool_use_id: string, tool_input: unknown, tool_response?: unknown) => ({ session_id, turn_id: "turn", cwd: "/project", hook_event_name, model: "gpt-5", tool_name: "Bash", tool_use_id, tool_input, tool_response });
runAdapterComplianceSuite(new CodexAdapter(), input("s", "PreToolUse", "a", { command: "pwd" }), input("s", "PostToolUse", "a", {}, { success: true }));
describe("Codex adapter", () => {
  it("normalizes Codex hooks", () => { const adapter = new CodexAdapter(); expect(adapter.normalizeBeforeAction(input("s", "PreToolUse", "a", { command: "pwd" }))).toMatchObject({ sessionId: "s", category: "shell" }); expect(adapter.normalizeAfterAction(input("s", "PostToolUse", "a", {}, { exit_code: 1, error: "failed" }))).toMatchObject({ success: false, exitCode: 1 }); });
  it("denies deterministic danger", async () => { const value = await root(); const output = await runCodexHook(value, input("s", "PreToolUse", "a", { command: "rm -rf /" }), provider); expect(output.hookSpecificOutput).toMatchObject({ permissionDecision: "deny" }); });
  it("queues one privileged replan and records canonical telemetry", async () => { const value = await root(); let output = {}; for (let index = 0; index < 3; index++) { const id = `a${index}`; await runCodexHook(value, input("s", "PreToolUse", id, { command: `pnpm install --retry=${index}` }), provider); output = await runCodexHook(value, input("s", "PostToolUse", id, {}, { success: false, error: "peer dependency failed" }), provider); } expect(output).toMatchObject({ hookSpecificOutput: { hookEventName: "PostToolUse", additionalContext: expect.stringContaining("ATHENA CONTROL") } }); expect(JSON.stringify(output)).not.toContain('"role":"user"'); const events = await new EventStore(join(value, ".athena", "events.jsonl")).read(); expect(events.some((event) => event.type === "REPLAN_QUEUED" && event.metadata.adapter === "codex")).toBe(true); expect(events.some((event) => event.type === "REPLAN_CONTEXT_APPLIED")).toBe(true); });
  it("keeps Codex sessions isolated and redacts telemetry", async () => { const value = await root(); await runCodexHook(value, input("A", "PreToolUse", "a", { token: "secret-value", command: "pwd" }), provider); await runCodexHook(value, input("B", "PreToolUse", "b", { command: "pwd" }), provider); const events = await new EventStore(join(value, ".athena", "events.jsonl")).read(); expect(new Set(events.map((event) => event.sessionId))).toEqual(new Set(["A", "B"])); expect(JSON.stringify(events)).not.toContain("secret-value"); });
  it("merges hooks idempotently without replacing existing handlers", () => { const source = { description: "user hooks", hooks: { PreToolUse: [{ matcher: "^Bash$", hooks: [{ type: "command", command: "user-hook" }] }] } }; const installed = mergeCodexHooks(source); expect(installed.hooks?.PreToolUse?.[0]).toEqual(source.hooks.PreToolUse[0]); expect(mergeCodexHooks(installed)).toEqual(installed); });
});
