#!/usr/bin/env node
import { access, mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import process from "node:process";
import { EventStore, createSession, defaultConfig, decide, loadConfig, saveConfig, stateFor, type AthenaMode } from "@athena/core";
import { DemoReflexProvider, TypeSafeReflexProvider } from "@athena/typesafe";

const root = process.cwd();
const line = (text: string) => process.stdout.write(`${text}\n`);
async function init() { const config = await loadConfig(root); await saveConfig(root, config); const plugin = join(root, ".opencode", "plugins", "athena.ts"); try { await access(plugin); line(`ATHENA initialized\nconfig     .athena/config.json\nplugin     exists: ${plugin}`); } catch { await mkdir(join(root, ".opencode", "plugins"), { recursive: true }); await writeFile(plugin, 'export { AthenaPlugin } from "@athena/opencode";\n'); line(`ATHENA initialized\nconfig     .athena/config.json\nplugin     ${plugin}`); } }
async function doctor(live = false) { const config = await loadConfig(root); const checks: Array<[string, boolean]> = [ [`Node ${process.versions.node}`, Number(process.versions.node.split(".")[0]) >= 20], ["configuration valid", true], ["OpenCode adapter installed", await exists(join(root, ".opencode", "plugins", "athena.ts"))], ["TYPESAFE_API_KEY found", Boolean(process.env.TYPESAFE_API_KEY) || config.provider === "demo"], ["event store writable", await writable()] ]; if (live) { if (!process.env.TYPESAFE_API_KEY) checks.push(["Jev live check", false]); else { const health = await new TypeSafeReflexProvider().health(); checks.push(["Jev reachable", health.reachable], ["response schema valid", health.schemaValid]); if (health.latencyMs !== undefined) line(`live reflex latency: ${health.latencyMs}ms`); } } line("ATHENA Doctor\n"); for (const [name, ok] of checks) line(`${ok ? "✓" : "✗"} ${name}`); line(checks.every(([, ok]) => ok) ? "\nATHENA is ready." : "\nSet TYPESAFE_API_KEY for real Jev, or set provider to demo for offline use."); }
async function exists(path: string) { try { await access(path); return true; } catch { return false; } }
async function writable() { try { await mkdir(join(root, ".athena"), { recursive: true }); await writeFile(join(root, ".athena", ".write-check"), "ok"); return true; } catch { return false; } }
async function status() { const config = await loadConfig(root); const events = await new EventStore(join(root, ".athena", "events.jsonl"), true).read(); const count = (type: string) => events.filter((event) => event.type === type).length; line(`ATHENA\n\nmode       ${config.mode}\nprovider   ${config.provider}\nagent      opencode\n\nsessions   ${new Set(events.map((event) => event.sessionId)).size}\nreflexes   ${count("REFLEX_COMPLETED")}\nallowed    ${count("ACTION_ALLOWED")}\nasked      ${count("ACTION_ASKED")}\ndenied     ${count("ACTION_DENIED")}\nreplans    ${count("REPLAN_REQUESTED")}`); }
async function mode(value?: string) { if (!value || !["shadow", "guardian", "balanced"].includes(value)) throw new Error("Usage: athena mode <shadow|guardian|balanced>"); const config = await loadConfig(root); await saveConfig(root, { ...config, mode: value as AthenaMode }); line(`ATHENA mode: ${value}`); }
async function events() { const list = await new EventStore(join(root, ".athena", "events.jsonl"), true).read(); for (const event of list) line(JSON.stringify(event)); }
function percentile(values: number[], ratio: number) { if (!values.length) return undefined; const sorted = [...values].sort((left, right) => left - right); return sorted[Math.min(sorted.length - 1, Math.ceil(sorted.length * ratio) - 1)]; }
async function report() { const config = await loadConfig(root); const events = await new EventStore(join(root, ".athena", "events.jsonl"), true).read(); const count = (type: string) => events.filter((event) => event.type === type).length; const latency = events.filter((event) => event.type === "REFLEX_COMPLETED").flatMap((event) => typeof event.metadata.latencyMs === "number" ? [event.metadata.latencyMs] : []); const reflex = (name: string) => events.filter((event) => event.type === "REFLEX_COMPLETED" && event.metadata.reflex === name).length; line(`ATHENA Session Report\n\nmode                 ${config.mode}\nprovider             ${config.provider}\nsessions             ${new Set(events.map((event) => event.sessionId)).size}\n\nAgent activity\ntool calls            ${count("ACTION_PROPOSED")}\nfailed actions        ${count("TOOL_FAILED")}\n\nJev\nreflex calls          ${count("REFLEX_COMPLETED")}\nfailures              ${count("REFLEX_FAILED")}\nmedian latency        ${percentile(latency, 0.5) ?? "n/a"}${latency.length ? "ms" : ""}\np95 latency           ${percentile(latency, 0.95) ?? "n/a"}${latency.length ? "ms" : ""}\n\nMETIS\nstagnation checks     ${reflex("stagnation")}\nreplans               ${count("REPLAN_REQUESTED")}\n\nAEGIS\nrisk checks           ${reflex("risk")}\ninterventions         ${count("ACTION_ASKED") + count("ACTION_DENIED")}\n\nNIKE\ncompletion checks     ${reflex("completion")}\nrejected              ${count("COMPLETION_REJECTED")}`); }
async function probe(name = "semantic-loop") { if (!process.env.TYPESAFE_API_KEY) throw new Error("TYPESAFE_API_KEY is required for a live probe. Run athena doctor --live."); const provider = new TypeSafeReflexProvider(); const session = createSession(name === "safe-action" ? "Fix package configuration" : "Fix a dependency installation failure"); const inputs = name === "real-progress" ? ["inspect package error", "inspect dependency tree", "change package version", "pnpm test"] : ["pnpm install", "pnpm install --force", "rm -rf node_modules && pnpm install", "pnpm install --legacy-peer-deps"]; for (const input of inputs) session.actions.push({ id: input, tool: "bash", input, timestamp: new Date().toISOString() }); const started = performance.now(); if (name === "safe-action" || name === "ambiguous-action") { const action = { id: "probe", tool: "bash", input: name === "safe-action" ? "cat package.json" : "sudo systemctl restart bluetooth", timestamp: new Date().toISOString() }; const risk = await provider.evaluateRisk(stateFor(session, action)); line(`ATHENA / LIVE PROBE\n\nprovider: typesafe\nscenario: ${name}\n\nrelevance             ${Math.round(risk.relevance * 100)}%\nunintended change     ${Math.round(risk.unintendedChange * 100)}%\napproval needed       ${Math.round(risk.approvalNeeded * 100)}%\n\nlatency               ${Math.round(performance.now() - started)}ms`); return; } if (name === "premature-completion") { const completion = await provider.evaluateCompletion(stateFor(session)); line(`ATHENA / LIVE PROBE\n\nprovider: typesafe\nscenario: ${name}\n\nrequirements met      ${Math.round(completion.requirementsSatisfied * 100)}%\nevidence works        ${Math.round(completion.evidenceWorks * 100)}%\nshould continue       ${Math.round(completion.shouldContinue * 100)}%\n\nlatency               ${Math.round(performance.now() - started)}ms`); return; } const stagnation = await provider.evaluateStagnation(stateFor(session)); line(`ATHENA / LIVE PROBE\n\nprovider: typesafe\nscenario: ${name}\n\nsame strategy         ${Math.round(stagnation.sameStrategy * 100)}%\nnew information       ${Math.round(stagnation.newInformation * 100)}%\nlikely progress       ${Math.round(stagnation.likelyToProgress * 100)}%\nstrategy change       ${Math.round(stagnation.strategyChangeNeeded * 100)}%\n\nlatency               ${Math.round(performance.now() - started)}ms`); }
async function demo() { line("ATHENA demo\nprovider: demo (simulated deterministic values; no TypeSafe API call)\n"); const provider = new DemoReflexProvider(); const session = createSession("Fix dependency installation without deleting project files"); const safe = { id: "1", tool: "bash", input: "pnpm install", timestamp: new Date().toISOString() }; session.actions.push(safe); const risk = await provider.evaluateRisk(stateFor(session, safe)); line(`AEGIS / safe action\n  decision  ${decide(defaultConfig, { action: safe, risk }).decision.toUpperCase()}\n  relevance ${Math.round(risk.relevance * 100)}%  risk ${Math.round(risk.unintendedChange * 100)}%\n`); line("METIS / normal progress\n  inspected error, dependency tree, then test result\n  decision  ALLOW\n"); for (const input of ["pnpm install", "pnpm install --force", "rm -rf node_modules && pnpm install", "pnpm install --legacy-peer-deps"]) session.actions.push({ id: input, tool: "bash", input, timestamp: new Date().toISOString() }); const stagnation = await provider.evaluateStagnation(stateFor(session)); const loop = decide({ ...defaultConfig, mode: "balanced" }, { action: session.actions.at(-1)!, stagnation }); line(`ATHENA / METIS\n\nSemantic stagnation detected\n\nsame strategy          ${Math.round(stagnation.sameStrategy * 100)}%\nnew information         ${Math.round(stagnation.newInformation * 100)}%\nlikely progress        ${Math.round(stagnation.likelyToProgress * 100)}%\nstrategy change        ${Math.round(stagnation.strategyChangeNeeded * 100)}%\n\n${loop.decision.toUpperCase()}\n`); const risky = { id: "2", tool: "bash", input: "sudo chmod -R 777 /", timestamp: new Date().toISOString() }; line(`AEGIS / risky action\n  decision  ${decide({ ...defaultConfig, mode: "balanced" }, { action: risky }).decision.toUpperCase()}\n  rule      privilege escalation\n`); session.results.push({ actionId: "x", success: false, output: "tests failed", timestamp: new Date().toISOString() }); const completion = await provider.evaluateCompletion(stateFor(session)); const finish = decide({ ...defaultConfig, mode: "balanced" }, { action: session.actions.at(-1)!, completion }); line(`NIKE / completion gate\n  evidence works ${Math.round(completion.evidenceWorks * 100)}%\n  continue       ${Math.round(completion.shouldContinue * 100)}%\n  ${finish.decision.toUpperCase()}`); }
const [command, argument] = process.argv.slice(2); const commands: Record<string, () => Promise<void>> = { init, doctor: () => doctor(argument === "--live"), status, mode: () => mode(argument), events, report, probe: () => probe(argument), demo, config: async () => { line(JSON.stringify(await loadConfig(root), null, 2)); } }; const selected = commands[command ?? ""]; if (selected) selected().catch((error: unknown) => { line(`ATHENA error: ${error instanceof Error ? error.message : String(error)}`); process.exitCode = 1; }); else line(command ? "Usage: athena <init|doctor [--live]|status|mode|config|events|report|probe|demo>" : "ATHENA: athena init");
